[project]
name = "markdown_util"
version = "0.1.0"
description = "A Python project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pystray>=0.19.5",
    "watchdog>=4.0",
]

[project.optional-dependencies]
ast = [
    "libmarkdown",
]

[tool.uv.sources]
libmarkdown = { path = "../libmarkdown" }

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
]
