#!/usr/bin/env python3
"""一键打包脚本（本地与 CI 共用同一逻辑）。

用法:
    python scripts/build.py              # 默认 onefile，打包两个 exe
    python scripts/build.py --onedir     # 用 onedir 模式（启动快，但是目录）
    python scripts/build.py --skip-rust  # 跳过 typora-uploader（调试 mdtool 时）
    python scripts/build.py --skip-py    # 跳过 mdtool

产物:
    dist/MdTool.exe                      # PySide6 版桌面管理器
    dist/typora-uploader.exe             # Typora 图片上传器（Rust）

依赖: uv（Python 侧）、cargo（Rust 侧），需在 PATH 中可用。
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UPLOADER = ROOT / "typora-uploader"
DIST = ROOT / "dist"

def _setup_utf8_stdio() -> None:
    """Windows runner（默认 cp1252）下打印中文会 UnicodeEncodeError，强制 UTF-8 输出。"""
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass


def run(cmd: list[str], cwd: Path, **kw) -> None:
    """运行命令，失败时抛异常带完整输出。"""
    print(f"\n$ {' '.join(cmd)}  (cwd={cwd.relative_to(ROOT)})", flush=True)
    subprocess.run(cmd, cwd=str(cwd), check=True, **kw)


# spec 模板（onefile / onedir 共用主体，仅 EXE 尾段不同）。统一生成到 build/
# 目录——spec 不入库，改模板只改这里。spec 落在 build/ 使 SPECPATH 不是仓库根，
# 因此入口脚本与 pathex 都要用 SPECPATH 拼出根的绝对路径（pyproject 同理）。
_SPEC_HEADER = """\
# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by scripts/build.py. Do not edit by hand.
"""

_SPEC_BODY = """\
import os
from PyInstaller.utils.hooks import collect_all

datas = []
# 根 pyproject.toml 随包打入：frozen 态 _version.py 从解包目录读版本号，
# 保持"根 pyproject 是版本唯一权威源"（build 期环境变量注入不可靠）。
_root = os.path.join(SPECPATH, os.pardir)
_root_pyproject = os.path.join(_root, 'pyproject.toml')
if os.path.exists(_root_pyproject):
    datas.append((_root_pyproject, '.'))
binaries = []
hiddenimports = [
    # core（后端）
    'mdtool.core.server.meta_db',
    'mdtool.core.server.media_server',
    'mdtool.core.server.notes_db',
    'mdtool.core.utils',
    'mdtool.core.link_resolver',
    'mdtool.core.kb_bundle',
    # desktop（Qt 界面层）
    'mdtool.desktop.qtui',
    'mdtool.desktop.qtui.widgets',
    'mdtool.desktop.qtui.icons',
    'mdtool.desktop.qtui.workers',
    'mdtool.desktop.qtui.theme',
    'mdtool.desktop.qtui.logbus',
    'mdtool.desktop.qtui.main_window',
    'mdtool.desktop.qtui.tabs.library',
    'mdtool.desktop.qtui.tabs.search',
    'mdtool.desktop.qtui.tabs.notes_browser',
    'mdtool.desktop.qtui.tabs.file_browser',
    'mdtool.desktop.qtui.tabs.media_server',
    'mdtool.desktop.qtui.tabs.space_fix',
    'mdtool.desktop.qtui.tabs.image_check',
    'mdtool.desktop.qtui.tabs.migrate',
]
# 轻量第三方包整体收集；PySide6 不做 collect_all（会把 WebEngine/3D 等
# 全部拖进来，体积 240MB+），改为显式列出用到的 Qt 模块，插件由 Qt hook 按需带出。
for pkg in ('libmarkdown', 'watchdog'):
    tmp = collect_all(pkg)
    datas += tmp[0]; binaries += tmp[1]; hiddenimports += tmp[2]
hiddenimports += ['PySide6.QtCore','PySide6.QtGui','PySide6.QtWidgets',
                  'PySide6.QtSvg','shiboken6']
a = Analysis([os.path.join(_root, 'mdtool', 'desktop', 'main_qt.py')],
             pathex=[_root], binaries=binaries, datas=datas,
             hiddenimports=hiddenimports, noarchive=False, optimize=0)
pyz = PYZ(a.pure)
"""

_ONEFILE_TAIL = """\
exe = EXE(pyz, a.scripts, a.binaries, a.datas, [],
          name='MdTool',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False,           # GUI app: no console window
          disable_windowed_traceback=False,
          argv_emulation=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None,
          icon=None,               # TODO: add an .ico later for taskbar/dock icon
)
"""

_ONEDIR_TAIL = """\
exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name='MdTool',
          console=False, upx=True)
coll = COLLECT(exe, a.binaries, a.datas, name='MdTool')
"""


def _write_spec(onefile: bool) -> Path:
    """生成 spec 到 build/ 目录，返回路径。"""
    build_dir = ROOT / "build"
    build_dir.mkdir(exist_ok=True)
    tail = _ONEFILE_TAIL if onefile else _ONEDIR_TAIL
    spec = build_dir / ("MdTool.spec" if onefile else "MdToolOnedir.spec")
    spec.write_text(_SPEC_HEADER + _SPEC_BODY + tail, encoding="utf-8")
    return spec


def build_rust() -> Path | None:
    """cargo build --release typora-uploader，返回产物路径。"""
    print("\n=== 构建 typora-uploader (Rust) ===", flush=True)
    try:
        run(["cargo", "build", "--release"], UPLOADER)
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"[WARN] typora-uploader 构建失败，跳过: {e}", file=sys.stderr)
        return None
    exe = UPLOADER / "target" / "release" / ("typora-uploader.exe" if os.name == "nt" else "typora-uploader")
    if not exe.exists():
        print(f"[WARN] 预期产物不存在: {exe}", file=sys.stderr)
        return None
    return exe


def build_python(ononedir: bool) -> Path | None:
    """uv run pyinstaller 打包 mdtool 桌面版，返回 exe 路径。

    打包模式（onefile/onedir）由 spec 文件本身决定——PyInstaller 不允许
    在给 .spec 时再用 --onefile/--onedir。spec 由 _write_spec 生成到 build/。

    用 ``python -m PyInstaller`` 而非 ``pyinstaller`` 入口 exe：uv 生成的
    script trampoline 在某些环境下会 "failed to canonicalize script path"，
    走模块入口绕过它，本地和 CI 都稳。
    """
    print("\n=== 构建 mdtool (PySide6 / PyInstaller) ===", flush=True)
    spec = _write_spec(onefile=not ononedir)
    args = [
        "uv", "run", "python", "-m", "PyInstaller", str(spec),
        "--noconfirm",
        "--distpath", str(DIST),
        "--workpath", str(ROOT / "build"),
    ]
    # 先同步子项目版本（libmarkdown / Cargo），保持 monorepo 版本一致。
    # 版本号本身不靠环境变量注入：spec 把根 pyproject.toml 打进包里，
    # frozen 态由 _version.py 从解包目录读取。
    try:
        subprocess.run([sys.executable, str(ROOT / "scripts" / "version.py"), "sync"], cwd=str(ROOT), check=True)
    except Exception:
        pass
    try:
        run(args, ROOT)
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"[ERROR] mdtool 构建失败: {e}", file=sys.stderr)
        return None
    # 产物路径：onefile → dist/MdTool.exe；onedir → dist/MdTool/MdTool.exe
    exe_name = "MdTool.exe" if os.name == "nt" else "MdTool"
    candidate = DIST / exe_name
    if candidate.exists():
        return candidate
    candidate = DIST / "MdTool" / exe_name
    if candidate.exists():
        return candidate
    print(f"[ERROR] 预期产物不存在: {candidate}", file=sys.stderr)
    return None


def human_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


def main(argv: list[str]) -> int:
    _setup_utf8_stdio()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--onedir", action="store_true", help="用 onedir 模式（默认 onefile）")
    ap.add_argument("--skip-rust", action="store_true", help="跳过 typora-uploader")
    ap.add_argument("--skip-py", action="store_true", help="跳过 mdtool")
    args = ap.parse_args(argv[1:])

    DIST.mkdir(exist_ok=True)
    # 清理旧产物，避免混淆（含改名前的 MarkdownUtilQt 遗留）
    for old in (DIST / "MarkdownUtilQt.exe", DIST / "MdTool.exe", DIST / "typora-uploader.exe"):
        if old.exists():
            old.unlink()
    for d in (DIST / "MarkdownUtilQt", DIST / "MdTool"):
        if d.is_dir():
            shutil.rmtree(d, ignore_errors=True)

    results: list[Path] = []

    if not args.skip_py:
        exe = build_python(args.onedir)
        if exe:
            results.append(exe)
    if not args.skip_rust:
        exe = build_rust()
        if exe:
            # 复制到 dist/（cargo 产物在 target/release 下）
            dest = DIST / ("typora-uploader.exe" if os.name == "nt" else "typora-uploader")
            shutil.copy2(exe, dest)
            results.append(dest)

    print("\n" + "=" * 50)
    print("打包完成，产物:")
    if not results:
        print("  (无产物)")
        return 1
    for p in results:
        size = human_size(p.stat().st_size)
        print(f"  {p.relative_to(ROOT)}  ({size})")
    print("=" * 50)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
