#!/usr/bin/env python3
"""一键打包脚本（本地与 CI 共用同一逻辑）。

用法:
    python scripts/build.py              # 默认 onefile，打包两个 exe
    python scripts/build.py --onedir     # 用 onedir 模式（启动快，但是目录）
    python scripts/build.py --skip-rust  # 跳过 typora-uploader（调试 markdown_util 时）
    python scripts/build.py --skip-py    # 跳过 markdown_util

产物:
    dist/MarkdownUtilQt.exe              # PySide6 版主程序
    dist/typora-uploader.exe             # Typora 图片上传器（Rust）

依赖: uv（Python 侧）、cargo（Rust 侧），需在 PATH 中可用。
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MD = ROOT / "markdown_util"
UPLOADER = ROOT / "typora-uploader"
DIST = ROOT / "dist"


def run(cmd: list[str], cwd: Path, **kw) -> None:
    """运行命令，失败时抛异常带完整输出。"""
    print(f"\n$ {' '.join(cmd)}  (cwd={cwd.relative_to(ROOT)})", flush=True)
    subprocess.run(cmd, cwd=str(cwd), check=True, **kw)


def _read_root_version_str() -> str | None:
    """读根 pyproject.toml 的 version 字符串，失败返回 None。"""
    try:
        import re
        text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
        m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
        return m.group(1) if m else None
    except Exception:
        return None


# onedir spec 模板：和 MarkdownUtilQt.spec 的 collect 配置一致，但用
# COLLECT 分发到目录（而不是把 binaries 塞进单 EXE）。由 build.py 在
# --onedir 时写入 build/MarkdownUtilQtOnedir.spec。
_ONEDIR_SPEC = """\
# -*- mode: python ; coding: utf-8 -*-
# AUTO-GENERATED by scripts/build.py (onedir variant). Do not edit by hand.
from PyInstaller.utils.hooks import collect_all
datas = []
binaries = []
hiddenimports = [
    'server.meta_db','server.media_server','server.notes_db','utils',
    'qtui','qtui.widgets','qtui.icons','qtui.workers','qtui.main_window',
    'qtui.tabs.notes_browser','qtui.tabs.file_browser','qtui.tabs.media_server',
    'qtui.tabs.space_fix','qtui.tabs.image_check','qtui.tabs.migrate',
]
for pkg in ('libmarkdown','mistletoe','PIL','pystray','watchdog','PySide6','shiboken6'):
    tmp = collect_all(pkg)
    datas += tmp[0]; binaries += tmp[1]; hiddenimports += tmp[2]
a = Analysis(['main_qt.py'], pathex=['.'], binaries=binaries, datas=datas,
             hiddenimports=hiddenimports, noarchive=False, optimize=0)
pyz = PYZ(a.pure)
exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name='MarkdownUtilQt',
          console=False, upx=True)
coll = COLLECT(exe, a.binaries, a.datas, name='MarkdownUtilQt')
"""


def _write_onedir_spec() -> Path:
    """写入 onedir spec 到 build/ 目录，返回路径。"""
    build_dir = ROOT / "build"
    build_dir.mkdir(exist_ok=True)
    spec = build_dir / "MarkdownUtilQtOnedir.spec"
    spec.write_text(_ONEDIR_SPEC, encoding="utf-8")
    return spec


def build_rust() -> Path | None:
    """cargo build --release typora-uploader，返回产物路径。"""
    print("\n=== 构建 typora-uploader (Rust) ===", flush=True)
    try:
        run(["cargo", "build", "--release"], UPLOADER)
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"[WARN] typora-uploader 构建失败，跳过: {e}", file=sys.stderr)
        return None
    exe = UPLOADER / "target" / "release" / ("typora-uploader.exe" if os.name == "nt" else "typora-uploader")
    if not exe.exists():
        print(f"[WARN] 预期产物不存在: {exe}", file=sys.stderr)
        return None
    return exe


def build_python(ononedir: bool) -> Path | None:
    """uv run pyinstaller 打包 markdown_util Qt 版，返回 exe 路径。

    打包模式（onefile/onedir）由 spec 文件本身决定——PyInstaller 不允许
    在给 .spec 时再用 --onefile/--onedir。onefile 用 MarkdownUtilQt.spec；
    onedir 走动态生成的临时 spec（复用同一套 collect 配置）。

    用 ``python -m PyInstaller`` 而非 ``pyinstaller`` 入口 exe：uv 生成的
    script trampoline 在某些环境下会 "failed to canonicalize script path"，
    走模块入口绕过它，本地和 CI 都稳。
    """
    print("\n=== 构建 markdown_util (PySide6 / PyInstaller) ===", flush=True)
    if ononedir:
        spec = _write_onedir_spec()
    else:
        spec = MD / "MarkdownUtilQt.spec"
    args = [
        "uv", "run", "python", "-m", "PyInstaller", str(spec),
        "--noconfirm",
        "--distpath", str(DIST),
        "--workpath", str(ROOT / "build"),
    ]
    # 注入版本号给打包后的 exe（_version.py 在 frozen 模式下读这个环境变量）。
    # 先同步子项目版本，确保 markdown_util/pyproject.toml 也是最新版本。
    try:
        subprocess.run([sys.executable, str(ROOT / "scripts" / "version.py"), "sync"], cwd=str(ROOT), check=True)
    except Exception:
        pass
    env = os.environ.copy()
    ver = _read_root_version_str()
    if ver:
        env["MDTOOL_VERSION"] = ver
    try:
        run(args, MD, env=env)
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"[ERROR] markdown_util 构建失败: {e}", file=sys.stderr)
        return None
    # 产物路径：onefile → dist/MarkdownUtilQt.exe；onedir → dist/MarkdownUtilQt/MarkdownUtilQt.exe
    exe_name = "MarkdownUtilQt.exe" if os.name == "nt" else "MarkdownUtilQt"
    candidate = DIST / exe_name
    if candidate.exists():
        return candidate
    candidate = DIST / "MarkdownUtilQt" / exe_name
    if candidate.exists():
        return candidate
    print(f"[ERROR] 预期产物不存在: {candidate}", file=sys.stderr)
    return None


def human_size(n: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} TB"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--onedir", action="store_true", help="用 onedir 模式（默认 onefile）")
    ap.add_argument("--skip-rust", action="store_true", help="跳过 typora-uploader")
    ap.add_argument("--skip-py", action="store_true", help="跳过 markdown_util")
    args = ap.parse_args(argv[1:])

    DIST.mkdir(exist_ok=True)
    # 清理旧产物，避免混淆
    for old in (DIST / "MarkdownUtilQt.exe", DIST / "typora-uploader.exe"):
        if old.exists():
            old.unlink()
    if (DIST / "MarkdownUtilQt").is_dir():
        shutil.rmtree(DIST / "MarkdownUtilQt", ignore_errors=True)

    results: list[Path] = []

    if not args.skip_py:
        exe = build_python(args.onedir)
        if exe:
            results.append(exe)
    if not args.skip_rust:
        exe = build_rust()
        if exe:
            # 复制到 dist/（cargo 产物在 target/release 下）
            dest = DIST / ("typora-uploader.exe" if os.name == "nt" else "typora-uploader")
            shutil.copy2(exe, dest)
            results.append(dest)

    print("\n" + "=" * 50)
    print("打包完成，产物:")
    if not results:
        print("  (无产物)")
        return 1
    for p in results:
        size = human_size(p.stat().st_size)
        print(f"  {p.relative_to(ROOT)}  ({size})")
    print("=" * 50)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
